name: Shell Commands1

on: [push]

jobs:
  abcd:
    runs-on: ubuntu-latest
    steps:
      - name: def
        run: echo "Hello World"
      - name: ghi script
        run: |
          node -v
          npm -v